version: '2'

services:
  consul:
    image: consul
    container_name: consul
    ports:
    - "8500:8500"

  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    network_mode: host
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    command: >
      -internal
      consul://localhost:8500
    depends_on:
    - consul

  nginx-noncanary:
    image: nginx
    container_name: nginx-noncanary
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: noncanary
    volumes:
    - ./www/index.html:/usr/share/nginx/html/index.html:ro


  nginx-canary:
      image: nginx
      container_name: nginx-canary
      environment:
        SERVICE_NAME: nginx
        SERVICE_TAGS: canary
      volumes:
      - ./www/canary.html:/usr/share/nginx/html/index.html:ro


  l5d:
    image: buoyantio/linkerd:1.3.6
    container_name: l5d
    ports:
    - "14140:4140"
    - "19990:9990"
    volumes:
    - ./linkerd.yaml:/io.buoyant/linkerd.yaml:ro
    - ../canary-identifier/target/scala-2.12/canaryIdentifier-assembly-0.1.jar:/io.buoyant/linkerd/1.3.6/plugins/canaryIdentifier-assembly-0.1.jar:ro
    command: >
      -log.level=DEBUG
      /io.buoyant/linkerd.yaml
